// Países e códigos de discagem (DDI), em ordem alfabética pt-BR.
// A bandeira vem como SVG local (public/bandeiras), não como emoji: o Windows
// não desenha emoji de bandeira e mostra as duas letras do país no lugar.
export const paises = [
  { iso: 'AF', nome: 'Afeganistão', ddi: '93' },
  { iso: 'ZA', nome: 'África do Sul', ddi: '27' },
  { iso: 'AL', nome: 'Albânia', ddi: '355' },
  { iso: 'DE', nome: 'Alemanha', ddi: '49' },
  { iso: 'AD', nome: 'Andorra', ddi: '376' },
  { iso: 'AO', nome: 'Angola', ddi: '244' },
  { iso: 'AI', nome: 'Anguila', ddi: '1' },
  { iso: 'AG', nome: 'Antígua e Barbuda', ddi: '1' },
  { iso: 'SA', nome: 'Arábia Saudita', ddi: '966' },
  { iso: 'DZ', nome: 'Argélia', ddi: '213' },
  { iso: 'AR', nome: 'Argentina', ddi: '54' },
  { iso: 'AM', nome: 'Armênia', ddi: '374' },
  { iso: 'AW', nome: 'Aruba', ddi: '297' },
  { iso: 'AU', nome: 'Austrália', ddi: '61' },
  { iso: 'AT', nome: 'Áustria', ddi: '43' },
  { iso: 'AZ', nome: 'Azerbaijão', ddi: '994' },
  { iso: 'BS', nome: 'Bahamas', ddi: '1' },
  { iso: 'BD', nome: 'Bangladesh', ddi: '880' },
  { iso: 'BB', nome: 'Barbados', ddi: '1' },
  { iso: 'BH', nome: 'Barein', ddi: '973' },
  { iso: 'BE', nome: 'Bélgica', ddi: '32' },
  { iso: 'BZ', nome: 'Belize', ddi: '501' },
  { iso: 'BJ', nome: 'Benin', ddi: '229' },
  { iso: 'BM', nome: 'Bermudas', ddi: '1' },
  { iso: 'BY', nome: 'Bielorrússia', ddi: '375' },
  { iso: 'BO', nome: 'Bolívia', ddi: '591' },
  { iso: 'BA', nome: 'Bósnia e Herzegovina', ddi: '387' },
  { iso: 'BW', nome: 'Botsuana', ddi: '267' },
  { iso: 'BR', nome: 'Brasil', ddi: '55' },
  { iso: 'BN', nome: 'Brunei', ddi: '673' },
  { iso: 'BG', nome: 'Bulgária', ddi: '359' },
  { iso: 'BF', nome: 'Burquina Faso', ddi: '226' },
  { iso: 'BI', nome: 'Burundi', ddi: '257' },
  { iso: 'BT', nome: 'Butão', ddi: '975' },
  { iso: 'CV', nome: 'Cabo Verde', ddi: '238' },
  { iso: 'CM', nome: 'Camarões', ddi: '237' },
  { iso: 'KH', nome: 'Camboja', ddi: '855' },
  { iso: 'CA', nome: 'Canadá', ddi: '1' },
  { iso: 'QA', nome: 'Catar', ddi: '974' },
  { iso: 'KZ', nome: 'Cazaquistão', ddi: '7' },
  { iso: 'TD', nome: 'Chade', ddi: '235' },
  { iso: 'CL', nome: 'Chile', ddi: '56' },
  { iso: 'CN', nome: 'China', ddi: '86' },
  { iso: 'CY', nome: 'Chipre', ddi: '357' },
  { iso: 'VA', nome: 'Cidade do Vaticano', ddi: '39' },
  { iso: 'CO', nome: 'Colômbia', ddi: '57' },
  { iso: 'KM', nome: 'Comores', ddi: '269' },
  { iso: 'CD', nome: 'Congo - Kinshasa', ddi: '243' },
  { iso: 'KP', nome: 'Coreia do Norte', ddi: '850' },
  { iso: 'KR', nome: 'Coreia do Sul', ddi: '82' },
  { iso: 'CI', nome: 'Costa do Marfim', ddi: '225' },
  { iso: 'CR', nome: 'Costa Rica', ddi: '506' },
  { iso: 'HR', nome: 'Croácia', ddi: '385' },
  { iso: 'CU', nome: 'Cuba', ddi: '53' },
  { iso: 'CW', nome: 'Curaçao', ddi: '599' },
  { iso: 'DK', nome: 'Dinamarca', ddi: '45' },
  { iso: 'DJ', nome: 'Djibuti', ddi: '253' },
  { iso: 'DM', nome: 'Dominica', ddi: '1' },
  { iso: 'EG', nome: 'Egito', ddi: '20' },
  { iso: 'SV', nome: 'El Salvador', ddi: '503' },
  { iso: 'AE', nome: 'Emirados Árabes Unidos', ddi: '971' },
  { iso: 'EC', nome: 'Equador', ddi: '593' },
  { iso: 'ER', nome: 'Eritreia', ddi: '291' },
  { iso: 'SK', nome: 'Eslováquia', ddi: '421' },
  { iso: 'SI', nome: 'Eslovênia', ddi: '386' },
  { iso: 'ES', nome: 'Espanha', ddi: '34' },
  { iso: 'SZ', nome: 'Essuatíni', ddi: '268' },
  { iso: 'US', nome: 'Estados Unidos', ddi: '1' },
  { iso: 'EE', nome: 'Estônia', ddi: '372' },
  { iso: 'ET', nome: 'Etiópia', ddi: '251' },
  { iso: 'FJ', nome: 'Fiji', ddi: '679' },
  { iso: 'PH', nome: 'Filipinas', ddi: '63' },
  { iso: 'FI', nome: 'Finlândia', ddi: '358' },
  { iso: 'FR', nome: 'França', ddi: '33' },
  { iso: 'GA', nome: 'Gabão', ddi: '241' },
  { iso: 'GM', nome: 'Gâmbia', ddi: '220' },
  { iso: 'GH', nome: 'Gana', ddi: '233' },
  { iso: 'GE', nome: 'Geórgia', ddi: '995' },
  { iso: 'GI', nome: 'Gibraltar', ddi: '350' },
  { iso: 'GD', nome: 'Granada', ddi: '1' },
  { iso: 'GR', nome: 'Grécia', ddi: '30' },
  { iso: 'GL', nome: 'Groenlândia', ddi: '299' },
  { iso: 'GP', nome: 'Guadalupe', ddi: '590' },
  { iso: 'GU', nome: 'Guam', ddi: '1' },
  { iso: 'GT', nome: 'Guatemala', ddi: '502' },
  { iso: 'GG', nome: 'Guernsey', ddi: '44' },
  { iso: 'GY', nome: 'Guiana', ddi: '592' },
  { iso: 'GF', nome: 'Guiana Francesa', ddi: '594' },
  { iso: 'GN', nome: 'Guiné', ddi: '224' },
  { iso: 'GQ', nome: 'Guiné Equatorial', ddi: '240' },
  { iso: 'GW', nome: 'Guiné-Bissau', ddi: '245' },
  { iso: 'HT', nome: 'Haiti', ddi: '509' },
  { iso: 'HN', nome: 'Honduras', ddi: '504' },
  { iso: 'HK', nome: 'Hong Kong, RAE da China', ddi: '852' },
  { iso: 'HU', nome: 'Hungria', ddi: '36' },
  { iso: 'YE', nome: 'Iêmen', ddi: '967' },
  { iso: 'CX', nome: 'Ilha Christmas', ddi: '61' },
  { iso: 'AC', nome: 'Ilha de Ascensão', ddi: '247' },
  { iso: 'IM', nome: 'Ilha de Man', ddi: '44' },
  { iso: 'NF', nome: 'Ilha Norfolk', ddi: '672' },
  { iso: 'AX', nome: 'Ilhas Aland', ddi: '358' },
  { iso: 'KY', nome: 'Ilhas Cayman', ddi: '1' },
  { iso: 'CC', nome: 'Ilhas Cocos (Keeling)', ddi: '61' },
  { iso: 'CK', nome: 'Ilhas Cook', ddi: '682' },
  { iso: 'FO', nome: 'Ilhas Faroé', ddi: '298' },
  { iso: 'FK', nome: 'Ilhas Malvinas', ddi: '500' },
  { iso: 'MP', nome: 'Ilhas Marianas do Norte', ddi: '1' },
  { iso: 'MH', nome: 'Ilhas Marshall', ddi: '692' },
  { iso: 'SB', nome: 'Ilhas Salomão', ddi: '677' },
  { iso: 'TC', nome: 'Ilhas Turcas e Caicos', ddi: '1' },
  { iso: 'VI', nome: 'Ilhas Virgens Americanas', ddi: '1' },
  { iso: 'VG', nome: 'Ilhas Virgens Britânicas', ddi: '1' },
  { iso: 'IN', nome: 'Índia', ddi: '91' },
  { iso: 'ID', nome: 'Indonésia', ddi: '62' },
  { iso: 'IR', nome: 'Irã', ddi: '98' },
  { iso: 'IQ', nome: 'Iraque', ddi: '964' },
  { iso: 'IE', nome: 'Irlanda', ddi: '353' },
  { iso: 'IS', nome: 'Islândia', ddi: '354' },
  { iso: 'IL', nome: 'Israel', ddi: '972' },
  { iso: 'IT', nome: 'Itália', ddi: '39' },
  { iso: 'JM', nome: 'Jamaica', ddi: '1' },
  { iso: 'JP', nome: 'Japão', ddi: '81' },
  { iso: 'JE', nome: 'Jersey', ddi: '44' },
  { iso: 'JO', nome: 'Jordânia', ddi: '962' },
  { iso: 'XK', nome: 'Kosovo', ddi: '383' },
  { iso: 'KW', nome: 'Kuwait', ddi: '965' },
  { iso: 'LA', nome: 'Laos', ddi: '856' },
  { iso: 'LS', nome: 'Lesoto', ddi: '266' },
  { iso: 'LV', nome: 'Letônia', ddi: '371' },
  { iso: 'LB', nome: 'Líbano', ddi: '961' },
  { iso: 'LR', nome: 'Libéria', ddi: '231' },
  { iso: 'LY', nome: 'Líbia', ddi: '218' },
  { iso: 'LI', nome: 'Liechtenstein', ddi: '423' },
  { iso: 'LT', nome: 'Lituânia', ddi: '370' },
  { iso: 'LU', nome: 'Luxemburgo', ddi: '352' },
  { iso: 'MO', nome: 'Macau, RAE da China', ddi: '853' },
  { iso: 'MK', nome: 'Macedônia do Norte', ddi: '389' },
  { iso: 'MG', nome: 'Madagascar', ddi: '261' },
  { iso: 'MY', nome: 'Malásia', ddi: '60' },
  { iso: 'MW', nome: 'Malaui', ddi: '265' },
  { iso: 'MV', nome: 'Maldivas', ddi: '960' },
  { iso: 'ML', nome: 'Mali', ddi: '223' },
  { iso: 'MT', nome: 'Malta', ddi: '356' },
  { iso: 'MA', nome: 'Marrocos', ddi: '212' },
  { iso: 'MQ', nome: 'Martinica', ddi: '596' },
  { iso: 'MU', nome: 'Maurício', ddi: '230' },
  { iso: 'MR', nome: 'Mauritânia', ddi: '222' },
  { iso: 'YT', nome: 'Mayotte', ddi: '262' },
  { iso: 'MX', nome: 'México', ddi: '52' },
  { iso: 'MM', nome: 'Mianmar (Birmânia)', ddi: '95' },
  { iso: 'FM', nome: 'Micronésia', ddi: '691' },
  { iso: 'MZ', nome: 'Moçambique', ddi: '258' },
  { iso: 'MD', nome: 'Moldávia', ddi: '373' },
  { iso: 'MC', nome: 'Mônaco', ddi: '377' },
  { iso: 'MN', nome: 'Mongólia', ddi: '976' },
  { iso: 'ME', nome: 'Montenegro', ddi: '382' },
  { iso: 'MS', nome: 'Montserrat', ddi: '1' },
  { iso: 'NA', nome: 'Namíbia', ddi: '264' },
  { iso: 'NR', nome: 'Nauru', ddi: '674' },
  { iso: 'NP', nome: 'Nepal', ddi: '977' },
  { iso: 'NI', nome: 'Nicarágua', ddi: '505' },
  { iso: 'NE', nome: 'Níger', ddi: '227' },
  { iso: 'NG', nome: 'Nigéria', ddi: '234' },
  { iso: 'NU', nome: 'Niue', ddi: '683' },
  { iso: 'NO', nome: 'Noruega', ddi: '47' },
  { iso: 'NC', nome: 'Nova Caledônia', ddi: '687' },
  { iso: 'NZ', nome: 'Nova Zelândia', ddi: '64' },
  { iso: 'OM', nome: 'Omã', ddi: '968' },
  { iso: 'NL', nome: 'Países Baixos', ddi: '31' },
  { iso: 'BQ', nome: 'Países Baixos Caribenhos', ddi: '599' },
  { iso: 'PW', nome: 'Palau', ddi: '680' },
  { iso: 'PA', nome: 'Panamá', ddi: '507' },
  { iso: 'PG', nome: 'Papua-Nova Guiné', ddi: '675' },
  { iso: 'PK', nome: 'Paquistão', ddi: '92' },
  { iso: 'PY', nome: 'Paraguai', ddi: '595' },
  { iso: 'PE', nome: 'Peru', ddi: '51' },
  { iso: 'PF', nome: 'Polinésia Francesa', ddi: '689' },
  { iso: 'PL', nome: 'Polônia', ddi: '48' },
  { iso: 'PR', nome: 'Porto Rico', ddi: '1' },
  { iso: 'PT', nome: 'Portugal', ddi: '351' },
  { iso: 'KE', nome: 'Quênia', ddi: '254' },
  { iso: 'KG', nome: 'Quirguistão', ddi: '996' },
  { iso: 'KI', nome: 'Quiribati', ddi: '686' },
  { iso: 'GB', nome: 'Reino Unido', ddi: '44' },
  { iso: 'CF', nome: 'República Centro-Africana', ddi: '236' },
  { iso: 'CG', nome: 'República do Congo', ddi: '242' },
  { iso: 'DO', nome: 'República Dominicana', ddi: '1' },
  { iso: 'RE', nome: 'Reunião', ddi: '262' },
  { iso: 'RO', nome: 'Romênia', ddi: '40' },
  { iso: 'RW', nome: 'Ruanda', ddi: '250' },
  { iso: 'RU', nome: 'Rússia', ddi: '7' },
  { iso: 'EH', nome: 'Saara Ocidental', ddi: '212' },
  { iso: 'WS', nome: 'Samoa', ddi: '685' },
  { iso: 'AS', nome: 'Samoa Americana', ddi: '1' },
  { iso: 'SM', nome: 'San Marino', ddi: '378' },
  { iso: 'SH', nome: 'Santa Helena', ddi: '290' },
  { iso: 'LC', nome: 'Santa Lúcia', ddi: '1' },
  { iso: 'BL', nome: 'São Bartolomeu', ddi: '590' },
  { iso: 'KN', nome: 'São Cristóvão e Névis', ddi: '1' },
  { iso: 'MF', nome: 'São Martinho', ddi: '590' },
  { iso: 'PM', nome: 'São Pedro e Miquelão', ddi: '508' },
  { iso: 'ST', nome: 'São Tomé e Príncipe', ddi: '239' },
  { iso: 'VC', nome: 'São Vicente e Granadinas', ddi: '1' },
  { iso: 'SC', nome: 'Seicheles', ddi: '248' },
  { iso: 'SN', nome: 'Senegal', ddi: '221' },
  { iso: 'SL', nome: 'Serra Leoa', ddi: '232' },
  { iso: 'RS', nome: 'Sérvia', ddi: '381' },
  { iso: 'SG', nome: 'Singapura', ddi: '65' },
  { iso: 'SX', nome: 'Sint Maarten', ddi: '1' },
  { iso: 'SY', nome: 'Síria', ddi: '963' },
  { iso: 'SO', nome: 'Somália', ddi: '252' },
  { iso: 'LK', nome: 'Sri Lanka', ddi: '94' },
  { iso: 'SD', nome: 'Sudão', ddi: '249' },
  { iso: 'SS', nome: 'Sudão do Sul', ddi: '211' },
  { iso: 'SE', nome: 'Suécia', ddi: '46' },
  { iso: 'CH', nome: 'Suíça', ddi: '41' },
  { iso: 'SR', nome: 'Suriname', ddi: '597' },
  { iso: 'SJ', nome: 'Svalbard e Jan Mayen', ddi: '47' },
  { iso: 'TJ', nome: 'Tadjiquistão', ddi: '992' },
  { iso: 'TH', nome: 'Tailândia', ddi: '66' },
  { iso: 'TW', nome: 'Taiwan', ddi: '886' },
  { iso: 'TZ', nome: 'Tanzânia', ddi: '255' },
  { iso: 'CZ', nome: 'Tchéquia', ddi: '420' },
  { iso: 'IO', nome: 'Território Britânico do Oceano Índico', ddi: '246' },
  { iso: 'PS', nome: 'Territórios palestinos', ddi: '970' },
  { iso: 'TL', nome: 'Timor-Leste', ddi: '670' },
  { iso: 'TG', nome: 'Togo', ddi: '228' },
  { iso: 'TK', nome: 'Tokelau', ddi: '690' },
  { iso: 'TO', nome: 'Tonga', ddi: '676' },
  { iso: 'TT', nome: 'Trinidad e Tobago', ddi: '1' },
  { iso: 'TA', nome: 'Tristão da Cunha', ddi: '290' },
  { iso: 'TN', nome: 'Tunísia', ddi: '216' },
  { iso: 'TM', nome: 'Turcomenistão', ddi: '993' },
  { iso: 'TR', nome: 'Turquia', ddi: '90' },
  { iso: 'TV', nome: 'Tuvalu', ddi: '688' },
  { iso: 'UA', nome: 'Ucrânia', ddi: '380' },
  { iso: 'UG', nome: 'Uganda', ddi: '256' },
  { iso: 'UY', nome: 'Uruguai', ddi: '598' },
  { iso: 'UZ', nome: 'Uzbequistão', ddi: '998' },
  { iso: 'VU', nome: 'Vanuatu', ddi: '678' },
  { iso: 'VE', nome: 'Venezuela', ddi: '58' },
  { iso: 'VN', nome: 'Vietnã', ddi: '84' },
  { iso: 'WF', nome: 'Wallis e Futuna', ddi: '681' },
  { iso: 'ZM', nome: 'Zâmbia', ddi: '260' },
  { iso: 'ZW', nome: 'Zimbábue', ddi: '263' }
];

export const PAIS_PADRAO = 'BR';

export const paisPadrao = paises.find((p) => p.iso === PAIS_PADRAO);

export const acharPais = (iso) =>
  paises.find((p) => p.iso === iso) ?? paisPadrao;

export const bandeira = (iso) => `/bandeiras/${iso.toLowerCase()}.svg`;
